import { MapBusiness } from "../types";

export const MOCK_MAP_BUSINESSES: MapBusiness[] = [
  {
    id: "mb-1",
    name: "Red Rock Brick Oven Trattoria",
    category: "Italian Restaurant",
    niche: "Restaurants",
    location: "Wichita, Kansas",
    address: "742 E Douglas Ave, Wichita, KS 67202",
    lat: 37.6865,
    lng: -97.332,
    phone: "+1 (316) 263-8820",
    website: "",
    websiteStatus: "No Website",
    websiteAnalysis: "🔥 High Opportunity: 4.8 stars with 420 reviews, but NO official website or online order system. Dependent on DoorDash 30% fees.",
    rating: 4.8,
    reviewCount: 420,
    priceLevel: "$$",
    email: "info@redrocktrattoria-wichita.com",
    whatsapp: "+1 (316) 263-8820",
    facebook: "https://facebook.com/redrocktrattoriaks",
    instagram: "https://instagram.com/redrocktrattoriaks",
    ceoName: "Marco Bellini",
    photos: [
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80",
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80",
    ],
    isOpenNow: true,
    verified: true,
  },
  {
    id: "mb-2",
    name: "Midwest Artisan Smokehouse & BBQ",
    category: "Barbecue Restaurant",
    niche: "Restaurants",
    location: "Wichita, Kansas",
    address: "1204 W Central Ave, Wichita, KS 67203",
    lat: 37.6912,
    lng: -97.351,
    phone: "+1 (316) 558-1902",
    website: "http://midwestsmokehousebbq-old.net",
    websiteStatus: "Redesign",
    websiteAnalysis: "⚠️ Needs Redesign: Built on 2014 WordPress. Takes 6.2s to load on mobile and PDF menu is unreadable on iPhones.",
    rating: 4.6,
    reviewCount: 310,
    priceLevel: "$$",
    email: "catering@midwestsmokehousebbq.com",
    whatsapp: "+1 (316) 558-1902",
    facebook: "https://facebook.com/midwestsmokehousebbq",
    ceoName: "Travis Vance",
    photos: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    ],
    isOpenNow: true,
    verified: true,
  },
  {
    id: "mb-3",
    name: "Prairie Prime Steakhouse",
    category: "Steakhouse & Fine Dining",
    niche: "Restaurants",
    location: "Wichita, Kansas",
    address: "3101 N Rock Rd, Wichita, KS 67226",
    lat: 37.7405,
    lng: -97.245,
    phone: "+1 (316) 634-1188",
    website: "https://prairieprimesteaks.com",
    websiteStatus: "SEO Performance",
    websiteAnalysis: "📉 SEO Opportunity: Missing Google schema markup for reservations. Missing high-intent local keywords for corporate events.",
    rating: 4.7,
    reviewCount: 580,
    priceLevel: "$$$",
    email: "vip@prairieprimesteaks.com",
    linkedin: "https://linkedin.com/company/prairie-prime-steakhouse",
    ceoName: "Gregory Hamilton",
    photos: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80",
    ],
    isOpenNow: false,
    verified: true,
  },
  {
    id: "mb-4",
    name: "Sunflower Craft Tacos & Cantina",
    category: "Mexican Restaurant",
    niche: "Restaurants",
    location: "Wichita, Kansas",
    address: "518 E 2nd St N, Wichita, KS 67202",
    lat: 37.6908,
    lng: -97.3305,
    phone: "+1 (316) 295-4411",
    website: "",
    websiteStatus: "No Website",
    websiteAnalysis: "🔥 High Opportunity: Only uses Facebook page. Customers frequently complain about outdated holiday hours and catering inquiries.",
    rating: 4.9,
    reviewCount: 290,
    priceLevel: "$",
    email: "hola@sunflowertacoswichita.com",
    whatsapp: "+1 (316) 295-4411",
    instagram: "https://instagram.com/sunflowertacos_ict",
    facebook: "https://facebook.com/sunflowertacosict",
    ceoName: "Mateo Alvarez",
    photos: [
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
    ],
    isOpenNow: true,
    verified: true,
  },
  {
    id: "mb-5",
    name: "Apex Precision Dental Care",
    category: "Cosmetic & Family Dentistry",
    niche: "Salons",
    location: "Austin, Texas",
    address: "2410 S Congress Ave, Austin, TX 78704",
    lat: 30.241,
    lng: -97.755,
    phone: "+1 (512) 441-2090",
    website: "http://apexprecisiondental-old.org",
    websiteStatus: "Redesign",
    websiteAnalysis: "⚠️ Needs Redesign: Non-HTTPS insecure certificate warnings on patient intake forms.",
    rating: 4.9,
    reviewCount: 340,
    priceLevel: "$$$",
    email: "intake@apexprecisiondental.com",
    whatsapp: "+1 (512) 441-2090",
    linkedin: "https://linkedin.com/in/dr-nathan-ellis-dds",
    ceoName: "Dr. Nathan Ellis",
    photos: [
      "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=600&q=80",
    ],
    isOpenNow: true,
    verified: true,
  },
  {
    id: "mb-6",
    name: "Hill Country Custom Home Builders",
    category: "General Contractor",
    niche: "Construction",
    location: "Austin, Texas",
    address: "8120 Research Blvd, Austin, TX 78758",
    lat: 30.365,
    lng: -97.718,
    phone: "+1 (512) 835-7740",
    website: "",
    websiteStatus: "No Website",
    websiteAnalysis: "🔥 Massive Lead Potential: Builds $800k+ custom homes. Currently has no online gallery portfolio to show prospects.",
    rating: 4.7,
    reviewCount: 88,
    priceLevel: "$$$$",
    email: "bids@hillcountrycustomtx.com",
    whatsapp: "+1 (512) 835-7740",
    linkedin: "https://linkedin.com/company/hill-country-builders-tx",
    ceoName: "Garrett Sterling",
    photos: [
      "https://images.unsplash.com/photo-1541888946425-d0fbb186156f?auto=format&fit=crop&w=600&q=80",
    ],
    isOpenNow: true,
    verified: true,
  },
  {
    id: "mb-7",
    name: "Lumina Glow Aesthetics & Laser",
    category: "Medical Spa & Skincare",
    niche: "Salons",
    location: "Miami, Florida",
    address: "950 Brickell Ave, Miami, FL 33131",
    lat: 25.764,
    lng: -80.191,
    phone: "+1 (305) 991-3344",
    website: "https://luminaglow-miami.com",
    websiteStatus: "SEO Performance",
    websiteAnalysis: "📉 SEO Opportunity: Ranking position #14 for 'Miami Botox & Laser'. A structured local citation campaign can boost to top 3.",
    rating: 4.9,
    reviewCount: 470,
    priceLevel: "$$$",
    email: "concierge@luminaglow-miami.com",
    whatsapp: "+1 (305) 991-3344",
    instagram: "https://instagram.com/luminaglow_miami",
    facebook: "https://facebook.com/luminaglowmiami",
    ceoName: "Valentina Gomez",
    photos: [
      "https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&w=600&q=80",
    ],
    isOpenNow: true,
    verified: true,
  },
  {
    id: "mb-8",
    name: "Titan Strength & Conditioning",
    category: "Athletic Gym & Training",
    niche: "Gyms",
    location: "Denver, Colorado",
    address: "1850 Blake St, Denver, CO 80202",
    lat: 39.753,
    lng: -104.996,
    phone: "+1 (303) 892-4411",
    website: "",
    websiteStatus: "No Website",
    websiteAnalysis: "🔥 High Opportunity: Over 600 monthly members using paper sign-in sheets. Missing automated membership and trial class funnel.",
    rating: 4.8,
    reviewCount: 195,
    priceLevel: "$$",
    email: "tyson@titanstrengthdenver.com",
    whatsapp: "+1 (303) 892-4411",
    instagram: "https://instagram.com/titanstrength_denver",
    ceoName: "Brock Reynolds",
    photos: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80",
    ],
    isOpenNow: true,
    verified: true,
  },
];
