// Comprehensive offline set of known disposable/temporary email domains
export const DISPOSABLE_DOMAINS = new Set([
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "10minutemailbox.com",
  "20minutemail.com",
  "2prong.com",
  "airmail.cc",
  "anonbox.net",
  "anonymbox.com",
  "antichef.com",
  "antichef.net",
  "armyspy.com",
  "baxomale.ht.cx",
  "brefmail.com",
  "burnermail.io",
  "cachedot.net",
  "chacuo.net",
  "crazymailing.com",
  "cuvox.de",
  "dayrep.com",
  "deadaddress.com",
  "despam.it",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "disposablemail.com",
  "dispostable.com",
  "drdrb.net",
  "dropmail.me",
  "dumpmail.de",
  "einrot.com",
  "emailondeck.com",
  "emailsensei.com",
  "emailtemporaneo.net",
  "emailwarden.com",
  "emltmp.com",
  "evopark.de",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "fastacura.com",
  "fleckens.hu",
  "fmail.cf",
  "fmail.ga",
  "fmail.gq",
  "fmail.ml",
  "generator.email",
  "getairmail.com",
  "getnada.com",
  "grr.la",
  "guerrillamail.biz",
  "guerrillamail.block",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "gustr.com",
  "harakirimail.com",
  "hidemail.de",
  "inbox.si",
  "inboxkitten.com",
  "incognitomail.org",
  "instantemailaddress.com",
  "jourrapide.com",
  "klzlk.com",
  "kurzepost.de",
  "lags.us",
  "mail-temporaire.fr",
  "mail-tester.com",
  "mailcatch.com",
  "maildrop.cc",
  "maildrop.cf",
  "maildrop.ga",
  "maildrop.gq",
  "maildrop.ml",
  "mailexpire.com",
  "mailforspam.com",
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinator2.com",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnesia.com",
  "mailnull.com",
  "mailsac.com",
  "mailtemp.net",
  "mailtothis.com",
  "mailtrash.net",
  "meltmail.com",
  "mohmal.com",
  "mohmal.in",
  "mohmal.tech",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "mytemp.email",
  "mytrashmail.com",
  "nada.ltd",
  "netmails.net",
  "nomail.xl.cx",
  "nospam.ze.tc",
  "nospam4.us",
  "nowmymail.com",
  "objectmail.com",
  "oneoffmail.com",
  "owlymail.com",
  "poeticpals.com",
  "pokemail.net",
  "postacin.com",
  "postonline.me",
  "quickinbox.com",
  "rcpt.at",
  "recode.me",
  "rhyta.com",
  "rootfest.net",
  "safetymail.info",
  "sandvikcoromant.email",
  "sharklasers.com",
  "shitmail.me",
  "shitmail.org",
  "shortmail.net",
  "sibmail.com",
  "smapmail.com",
  "sofort-mail.de",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spamevader.com",
  "spamfree24.org",
  "spamgourmet.com",
  "spamhole.com",
  "spaml.de",
  "spamspot.com",
  "superrito.com",
  "suremail.info",
  "tafmail.com",
  "teewars.org",
  "teleworm.us",
  "temp-mail.de",
  "temp-mail.org",
  "temp-mail.ru",
  "tempail.com",
  "tempemail.co",
  "tempemail.net",
  "tempinbox.com",
  "tempmail.de",
  "tempmail.net",
  "tempmail.org",
  "tempmail.us",
  "tempmail24.com",
  "tempmailaddress.com",
  "temporaryemail.net",
  "temppost.com",
  "throwawayemailaddress.com",
  "throwawaymail.com",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trashmail.at",
  "trashmail.com",
  "trashmail.de",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.ws",
  "trashmailer.com",
  "tvch.de",
  "twinmail.de",
  "upfortress.com",
  "urhen.com",
  "vmani.com",
  "vomoto.com",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "whyspam.me",
  "wr.monemail.fr.nf",
  "xagloo.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "ypmail.webcam",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoemail.org",
]);

export function isDisposableDomain(domain: string): boolean {
  if (!domain) return false;
  const d = domain.toLowerCase().trim();
  if (DISPOSABLE_DOMAINS.has(d)) return true;

  // Catch common disposable service prefixes
  if (
    /^temp[-_.]?mail\./i.test(d) ||
    /^tempemail\./i.test(d) ||
    /^throwaway/i.test(d) ||
    /^guerrilla/i.test(d) ||
    /^mailinator/i.test(d) ||
    /^10minute/i.test(d) ||
    /^20minute/i.test(d) ||
    /^dispos/i.test(d) ||
    /^yopmail/i.test(d) ||
    /^trashmail/i.test(d) ||
    /^burnermail/i.test(d) ||
    /^sharklasers/i.test(d) ||
    /^fakeinbox/i.test(d)
  ) {
    return true;
  }

  // Check subdomains
  const parts = d.split(".");
  if (parts.length > 2) {
    const parentDomain = parts.slice(-2).join(".");
    if (DISPOSABLE_DOMAINS.has(parentDomain)) return true;
  }
  return false;
}
