// Well-known public free email provider domains
export const FREE_EMAIL_PROVIDERS = new Set([
  "gmail.com",
  "googlemail.com",
  "yahoo.com",
  "yahoo.co.uk",
  "yahoo.fr",
  "yahoo.es",
  "yahoo.de",
  "yahoo.it",
  "yahoo.ca",
  "yahoo.com.au",
  "yahoo.com.br",
  "yahoo.co.jp",
  "ymail.com",
  "rocketmail.com",
  "hotmail.com",
  "hotmail.co.uk",
  "hotmail.fr",
  "hotmail.es",
  "hotmail.de",
  "hotmail.it",
  "outlook.com",
  "outlook.fr",
  "outlook.es",
  "outlook.de",
  "outlook.co.uk",
  "live.com",
  "live.co.uk",
  "live.fr",
  "msn.com",
  "passport.com",
  "icloud.com",
  "me.com",
  "mac.com",
  "aol.com",
  "aim.com",
  "proton.me",
  "protonmail.com",
  "protonmail.ch",
  "zoho.com",
  "zohomail.com",
  "mail.com",
  "email.com",
  "usa.com",
  "post.com",
  "gmx.com",
  "gmx.net",
  "gmx.de",
  "gmx.at",
  "gmx.ch",
  "web.de",
  "t-online.de",
  "yandex.com",
  "yandex.ru",
  "mail.ru",
  "inbox.ru",
  "list.ru",
  "bk.ru",
  "rambler.ru",
  "fastmail.com",
  "fastmail.fm",
  "hushmail.com",
  "tutanota.com",
  "tutamail.com",
  "rediffmail.com",
  "sina.com",
  "qq.com",
  "163.com",
  "126.com",
  "yeah.net",
  "naver.com",
  "daum.net",
  "hanmail.net",
  "orange.fr",
  "wanadoo.fr",
  "free.fr",
  "sfr.fr",
  "laposte.net",
  "libero.it",
  "virgilio.it",
  "alice.it",
  "tiscali.it",
  "bluewin.ch",
  "skynet.be",
  "telenet.be",
  "shaw.ca",
  "sympatico.ca",
  "rogers.com",
  "bell.net",
  "telus.net",
  "comcast.net",
  "verizon.net",
  "att.net",
  "sbcglobal.net",
  "charter.net",
  "cox.net",
]);

export function isFreeEmailProvider(domain: string): boolean {
  if (!domain) return false;
  const d = domain.toLowerCase().trim();
  if (FREE_EMAIL_PROVIDERS.has(d)) return true;

  const parts = d.split(".");
  if (parts.length > 2) {
    const parent = parts.slice(-2).join(".");
    if (FREE_EMAIL_PROVIDERS.has(parent)) return true;
  }
  return false;
}
